name: CI for API & frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_test_api:
    name: API layer build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build & test API layer with Maven
      run: cd api && mvn -B package --file pom.xml
  test_lint_build_frontend:
    name: Frontend test, lint and build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - name: Test frontend
      run: cd web && npm test run
    - name: Lint frontend
      run: npm run lint
    - name: Build Frontend
      run: npm run build
